apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: b0szh4g88-go-gitops
  description: This is GitOps manifest for b0szh4g88-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=b0szh4g88-go
    backstage.io/kubernetes-id: b0szh4g88-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: b0szh4g88-go
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:b0szh4g88-go
